# Generated by Django 5.2.4 on 2025-07-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('sucess', 'Sucess'), ('error', 'Error')], max_length=12),
        ),
    ]
