# Generated by Django 5.2.4 on 2025-07-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=12),
        ),
    ]
