# Generated by Django 5.2.4 on 2025-07-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='events.category'),
        ),
    ]
