# Generated by Django 5.2.4 on 2025-07-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_category_events_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='batch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.batch'),
        ),
    ]
