# Generated by Django 5.2.4 on 2025-07-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(blank=True, to='events.category'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.location'),
        ),
    ]
