# Generated by Django 5.2.4 on 2025-07-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_category_alter_events_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField()),
                ('sympla_id', models.CharField(max_length=128, unique=True)),
                ('batch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.batch')),
                ('category', models.ManyToManyField(blank=True, to='events.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
